#!/bin/sh -e

. pkg

pkg="heirloom-toolchest"
version="1.0"
category="base"
arch="x86_64"
basedir="/"
pstamp="$version"
name="heirloom toolchest"
source="https://github.com/rtomj/heirloom-project/archive/v1.0.tar.gz"
deps=""

#mkdir -p /tmp/"$pkg"
#wget "$source"
tar xf v"$version".tar.gz

cd heirloom-project-1.0/heirloom/heirloom/build
sed -i '22s/ROOT =/ROOT= \/tmp\/heirloom-toolchest/' mk.config
cd ..
make
make install

mkpkg

