#!/bin/sh

. pkg

pkg="dmenu"
version="4.9"
category="x11"
arch="x86_64"
source="http://dl.suckless.org/tools/$pkg-$version.tar.gz"
basedir="/"
pstamp="$version"
name="dynamic menu"
        

wget "$source"
tar xf "$pkg"-"$version".tar.gz

cd "$pkg"-"$version"

DESTDIR=/tmp/"$pkg" make install

mkpkg
