#!/bin/sh

. /usr/bin/pkg

pkg=tcsh
version="6.20.00"
category=base
arch="x86_64"
basedir="/"
pstamp="$version"
name="enhanced C shell"
source="ftp://ftp.astron.com/pub/tcsh/$pkg-$version.tar.gz"


mkdir -p /tmp/$pkg

wget $source
tar xf "$pkg"-"$version".tar.gz

cd "$pkg"-$version

./configure --prefix=/usr --bindir=/bin --disable-nls
make
make DESTDIR=/tmp/$pkg install

mkpkg

