#!/bin/sh

. pkg

pkg=giflib
version="5.1.4"
category=graphics
arch="x86_64"
basedir="/"
pstamp="$version"
name="compressed GIF library"
source="http://download.sourceforge.net/$pkg/$pkg-$version.tar.bz2"

mkdir -p /tmp/$pkg

wget "$source"
tar xf "$pkg"-"$version".tar.bz2

cd "$pkg"-$version

./configure --prefix=/usr/local
make
make prefix=/tmp/$pkg/usr/local install

mkpkg

