#!/bin/sh

. pkg

pkg=ranger
version="1.9.2"
category="x11"
arch="x86_64"
source="https://github.com/ranger/ranger/archive/v1.9.2.tar.gz"
basedir="/"
pstamp="$version"
name="CLI filemanger"
        
wget "$source"
tar xf v"$version".tar.gz
cd "$pkg"-"$version"

mkdir -p /tmp/$pkg
DESTDIR=/tmp/$pkg make install

mkpkg

