#!/bin/sh 

. pkg

pkg=pkgtools
version=0.9.0
category=base
arch="x86_64"
basedir="/"
pstamp="$version"
name="frontend for heirloom SVR4 pkgtools"


mkdir -p /tmp/"$pkg"
cd "$pkg"
install -c pkg /tmp/"$pkg"/usr/bin/pkg
install -c pkgbuild /tmp/"$pkg"/usr/bin/pkgbuild
install -c heirloom-pkg /tmp/$pkg/usr/bin/heirloom-pkg
install -c heirloom-pkgbuild /tmp/$pkg/usr/bin/heirloom-pkgbuild

mkpkg

