#!/bin/sh

. pkg

# the binary will be 'ksh'
pkg=loksh
version="6.4"
category=shells
arch="x86_64"
basedir="/"
pstamp="$version"
name="OpenBSD's ksh"
source="https://github.com/dimkr/loksh/archive/6.4/$pkg-$version.tar.gz"

mkdir -p /tmp/"$pkg"

wget "$source"
tar xf "$pkg"-"$version".tar.gz

cd "$pkg"-$version

make
make install \
	PREFIX=/usr/local \
	DESTDIR=/tmp/"$pkg"
	
cd /tmp/"$pkg"
ln -s /tmp/$pkg/usr/local/bin/$pkg /bin/ksh

mkpkg

