#!/bin/sh

. pkg

pkg=libvorbis
version="1.3.6"
category=audio
arch="x86_64"
basedir="/"
pstamp="$version"
name="Vorbis codec library"
source="https://downloads.xiph.org/releases/vorbis/$pkg-$version.tar.xz"
deps="audio/libogg"

mkdir -p /tmp/$pkg

wget "$source"
xzcat $pkg-$version.tar.xz | tar xf -

cd "$pkg"-$version

./configure --prefix=/usr/local

make
make DESTDIR=/tmp/$pkg install


mkpkg

