#!/bin/sh -e

. pkg

pkg="heirloom-pkgtools"
version="1.0"
category="base"
arch="x86_64"
basedir="/"
pstamp="$version"
name="heirloom pkgtools"
source="https://github.com/rtomj/heirloom-project/archive/v1.0.tar.gz"
deps=""

mkdir -p /tmp/"$pkg"/var
#wget "$source"
tar xf v"$version".tar.gz

cd heirloom-project-1.0/heirloom/heirloom-pkgtools	
sed -i '21s/PREFIX=\/usr/PREFIX=\/tmp\/heirloom-pkgtools/' mk.config
sed -i '22s/VAR=\/var/PREFIX=\/tmp\/heirloom-pkgtools/' mk.config
make
make install 

mkpkg

