#!/bin/sh

. /usr/bin/pkg

pkg=linux
version=4.19.19
category=base
arch="x86_64"
basedir="/"
pstamp="$version"
name="Linux LTS kernel"
source="https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.19.tar.xz"

mkdir -p /tmp/"$pkg"/boot

wget "$source"
xzcat "$pkg"-"$version".tar.xz | tar xf -

cd "$pkg"-$version

zcat /proc/config.gz > .config
#uncomment if needed
#make menuconfig
make -j4 all
make -j4 modules_install DESTDIR=/tmp/$pkg

cp arch/x86/boot/bzImage /tmp/$pkg/boot/vmlinuz-$version
cp System.map /tmp/$pkg/boot

mkpkg

