#!/bin/sh

. pkg

pkg=help2man
version=1.47.8
category=doc
arch="x86_64"
basedir="/"
pstamp="$version"
name="generates man pages"
source="http://ftp.gnu.org/gnu/help2man/help2man-1.47.8.tar.xz"

mkdir -p /tmp/"$pkg"

wget "$source"
xzcat "$pkg"-"$version".tar.xz | tar xf -

cd "$pkg"-$version

./configure \
	--prefix=/usr/local \
	--mandir=/usr/local/man \
	--disable-nls
make
make DESTDIR=/tmp/"$pkg" install

mkpkg

