#!/bin/sh

. pkg

pkg=tree
version="1.8.0"
category=sysutils
arch="x86_64"
basedir="/"
pstamp="$version"
name="display directory tree"
source="ftp://mama.indstate.edu/linux/$pkg/$pkg-$version.tgz"
deps="libraries/libnotify"

mkdir -p /tmp/$pkg

wget "$source"
tar xf "$pkg"-"$version".tgz

cd "$pkg"-$version

make

install -D -m 0755 $pkg /tmp/$pkg/usr/local/bin/$pkg

install -D -m 0644 doc/$pkg.1 /tmp/$pkg/usr/local/share/man/man1/$pkg.1

mkpkg

