#!/bin/sh

. pkg

pkg=libgudev
version="232"
category=devel
arch="x86_64"
basedir="/"
pstamp="$version"
name="GIbject bindings"
source="https://ftp.gnome.org/pub/gnome/sources/$pkg/$version/$pkg-$version.tar.xz"
mkdir -p /tmp/$pkg

wget "$source"
xzcat "$pkg"-"$version".tar.xz | tar xf -

cd "$pkg"-$version

./configure --prefix=/usr/local
make
make install DESTDIR=/tmp/$pkg

mkpkg

