#!/bin/sh

. /usr/bin/pkg

pkg=elilo
version=3.16
category=base
arch=x86_64
basedir="/"
pstamp=$version
name="elilo boot manager"
source="https://mirrors.slackware.com/slackware/slackware-current/source/a/elilo/elilo-3.16-all.tar.xz"
source2="https://mirrors.slackware.com/slackware/slackware-current/source/a/elilo/elilo.loader.binaries.tar.xz"
deps="base/gnu-efi"

mkdep
wget "$source"
wget "$source2"

mkdir -p /tmp/$pkg/usr/sbin

xzcat elilo-$version-all.tar.xz | tar xf -
xzcat elilo.loader.binaries.tar.xz | tar xf -
tar xf elilo-$version-source.tar.gz

mkdir -p /tmp/$pkg/boot/efi/EFI/elilo
cp elilo-3.16-x86_64.efi /tmp/$pkg/boot/efi/EFI/elilo/elilo.efi

cd elilo-$version-source

cp tools/eliloalt /tmp/$pkg/usr/sbin

mkpkg
