#!/bin/sh

. pkg

pkg=libsndfile
version="1.0.28"
category=audio
arch="x86_64"
basedir="/"
pstamp="$version"
name="library for manipulating sound files"
source="http://www.mega-nerd.com/$pkg/files/$pkg-$version.tar.gz"
deps="audio/flac audio/libvorbis"

mkdep
mkdir -p /tmp/$pkg

wget $source
tar xf "$pkg"-"$version".tar.gz

cd "$pkg"-$version

./configure \
	--prefix=/usr/local \
	--disable-static \
	--with-pic

make
make DESTDIR=/tmp/$pkg install

rm -r /tmp/$pkg/usr/local/share/doc

mkpkg

