#!/bin/sh

. pkg

pkg=expat
version="2.2.6"
category=textproc
arch="x86_64"
basedir="/"
pstamp="$version"
name="XML parsing library"
source="http://download.sourceforge.net/$pkg/$pkg-$version.tar.bz2"

mkdir -p /tmp/$pkg

wget "$source"
tar xf "$pkg"-"$version".tar.bz2

cd "$pkg"-$version

./configure --prefix=/usr/local
make
make DESTDIR=/tmp/$pkg install

mkpkg

