#!/bin/sh

. pkg

pkg=libsigsegv
version=2.11
category=libraries
arch="x86_64"
basedir="/"
pstamp="$version"
name="page fault handler"
source="http://ftp.gnu.org/gnu/$pkg/$pkg-$version.tar.gz"

mkdir -p /tmp/$pkg

wget "$source"
tar xf "$pkg"-"$version".tar.gz

cd "$pkg"-$version

./configure \
	--prefix=/usr/local \
	--enable-shared
make
make install DESTDIR=/tmp/$pkg

mkpkg

