#!/bin/sh

. /usr/bin/pkg

pkg=gnu-efi
version=3.0.9
category=base
arch=x86_64
basedir="/"
pstamp=$version
name="GNU efi library"
source="http://download.sourceforge.net/$pkg/$pkg-$version.tar.bz2"

wget "$source"
tar xf "$pkg"-"$version".tar.bz2
mkdir -p /tmp/"$pkg"
  
cd "$pkg"-"$version"
make
make INSTALLROOT=/tmp/"$pkg" PREFIX=/usr/local install
mkpkg


