#!/bin/sh

. pkg

pkg=icecat
version=60.3.0
category=net
arch="x86_64"
basedir="/opt/$pkg"
pstamp="$version"
name="GNU fork of Mozilla Firefox"
source="https://ftp.gnu.org/gnu/gnuzilla/60.3.0/icecat-60.3.0.en-US.gnulinux-x86_64.tar.bz2"

mkdir -p /tmp/"$pkg"
wget "$source"
tar xf "$pkg"-"$version".en-US.gnulinux-x86_64.tar.bz2

cd "$pkg"
install -D /tmp/$pkg
cd /tmp/"$pkg"

mkpkg

