#!/bin/sh 

. /usr/bin/pkg

pkg=ex
version=050325
category=editors
arch="x86_64"
source="http://downloads.sourceforge.net/project/ex-vi/ex-vi/"$version"/ex-"$version".tar.bz2"
basedir="/"
pstamp="$version"
name="traditional vi"

wget $source
tar xf $pkg-$version.tar.bz2

cd "$pkg"-"$version"
mkdir -p /tmp/$pkg
make install DESTDIR=/tmp/$pkg

mkpkg
