#!/bin/sh

. pkg

pkg=mit-scheme
version="9.2"
category=lang
arch="x86_64"
basedir="/"
pstamp="$version"
name="Scheme implementation"
source="http://ftp.gnu.org/gnu/mit-scheme/stable.pkg/9.2/mit-scheme-9.2-x86-64.tar.gz"

mkdir -p /tmp/$pkg

wget "$source"
tar xf $pkg-$version-x86-64.tar.gz

cd "$pkg"-$version
cd src
./configure \
	--prefix=/usr/local \
	--libdir=/usr/local/lib
make
make install DESTDIR=/tmp/$pkg

mkpkg

